@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jul 04 22:58:36 +0530 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim processor_tb_behav -key {Behavioral:sim_1:Functional:processor_tb} -tclbatch processor_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/menuw/Documents/Processor-Design/project_1/sim1_behav.wcfg -view C:/Users/menuw/Documents/Processor-Design/project_1/processor_tb_dmem.wcfg -view C:/Users/menuw/Documents/Processor-Design/project_1/mem_register.wcfg -view C:/Users/menuw/Documents/Processor-Design/project_1/last4registers.wcfg -log simulate.log"
call xsim  processor_tb_behav -key {Behavioral:sim_1:Functional:processor_tb} -tclbatch processor_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/menuw/Documents/Processor-Design/project_1/sim1_behav.wcfg -view C:/Users/menuw/Documents/Processor-Design/project_1/processor_tb_dmem.wcfg -view C:/Users/menuw/Documents/Processor-Design/project_1/mem_register.wcfg -view C:/Users/menuw/Documents/Processor-Design/project_1/last4registers.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
